'use client';

import { useState, type FormEvent } from 'react';
import { api } from '@/lib/api';

type AskResult = {
  answer: string;
  sources: { file: string; score: number }[];
};

const EXAMPLES = [
  'What time do you close on Saturday?',
  'How much is a consultation for a child?',
  'Can I get an MC without seeing the doctor?',
  'When will my lab results be ready?',
];

export default function AssistantPage() {
  const [question, setQuestion] = useState('');
  const [result, setResult] = useState<AskResult | null>(null);
  const [thinking, setThinking] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function ask(q: string) {
    if (!q.trim()) return;
    setQuestion(q);
    setThinking(true);
    setError(null);
    setResult(null);
    try {
      setResult(
        await api<AskResult>('/ai/ask', {
          method: 'POST',
          body: JSON.stringify({ question: q.trim() }),
        }),
      );
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setThinking(false);
    }
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    ask(question);
  }

  return (
    <section className="card">
      <h2>🤖 Clinic Assistant</h2>
      <p>Ask about opening hours, fees, services or clinic policies.</p>

      <div className="chips">
        {EXAMPLES.map((ex) => (
          <button key={ex} type="button" className="secondary" onClick={() => ask(ex)} disabled={thinking}>
            {ex}
          </button>
        ))}
      </div>

      <form onSubmit={handleSubmit} noValidate>
        <input
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          placeholder="Type your question..."
          maxLength={500}
        />
        <button type="submit" disabled={thinking || question.trim() === ''}>
          {thinking ? 'Thinking...' : 'Ask'}
        </button>
      </form>

      {error && <p className="error">⚠️ {error}</p>}

      {result && (
        <div className="answer">
          <p>{result.answer}</p>
          {result.sources.length > 0 && (
            <small>
              📄 Sources: {result.sources.map((s) => `${s.file} (${s.score})`).join(', ')}
            </small>
          )}
        </div>
      )}

      <p className="disclaimer">
        ⓘ Answers are generated by AI from clinic documents. For medical advice, please see our doctor.
      </p>
    </section>
  );
}